
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-site-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="sk">
    <head>
      <meta charset="UTF-8">
      <title>Test2</title>
    </head>
    <body>
      <h1>K8s test web</h1>
      <p>Lukac</p>
    </body>
    </html>
