
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-site-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="sk">
    <head>
      <meta charset="UTF-8">
      <title>Test2</title>
    </head>
    <body>
      <h1>Ahoj 👋</h1>
      <p>Toto je moja jednoduchá HTML stránka bežiaca na Kubernetes cez Argo CD.</p>
    </body>
    </html>
