apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-site
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mirec30/simple-html-site.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
